# Generated by Django 6.1 on 2026-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_failed_login_attempts_profile_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
