# Generated by Django 6.1 on 2026-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_default_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
